# //// Neoffice — added file (multi-warehouse feature). Hidden marker on
# //// Purchase Order so the procurement pilot can find "the" open webshop
# //// draft of a supplier and stack new order lines into it.

import frappe


def execute():
	if frappe.db.exists(
		"Custom Field", {"dt": "Purchase Order", "fieldname": "neo_webshop_generated"}
	):
		return

	frappe.get_doc(
		{
			"doctype": "Custom Field",
			"dt": "Purchase Order",
			"fieldname": "neo_webshop_generated",
			"label": "Generated by Webshop",
			"fieldtype": "Check",
			"insert_after": "supplier",
			"default": "0",
			"hidden": 1,
			"no_copy": 1,
			"owner": "Administrator",
		}
	).insert(ignore_permissions=True)
	frappe.db.commit()
